# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jinka Venkata Sai Kiran
title: Software Engineer and Content Writer 
email: kiranjv888@outlook.com
website: https://bit.ly/3fMA1Y4 

# Social links
twitter_username: saikiranjv
github_username:  kiranjv888
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: sai-kiran-jv-028609a2
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kiran and I'm a senior software engineer. As well as design and develpment of embedded application development I also have experience in board bringup, machine learning and performance optimization. I have worked with different teams gaining teamwork and leadership skills.

  I am most skilled in: <mark>Linux Internals</mark>, <mark>Networking</mark> and <mark>Food Diet</mark>

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Jogging
   - Playing Cricket & Football
   - Reading Books & Analysing Business
   - Blogging

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
